### ISSUE TITLE
Terminal iframe not being loaded from same domain

### ISSUE THREAD

**Issue by Laphatize** [ctfguide-tech/CTFGuideNext#8]
If we want to allow streaming of terminal data and we're relying on input from the browser itself - I need to be able to run some javascript on the iframe.

Since the domain of the iframe is terminal.ctfguide.com - it will not allow me to control it. However, if it was something like ctfguide.com/terminal - I would be able to control it.

I am labelling this as enhancement for now because cloud support won't be introduced until late summer.

**Comment by raymond-design** [comment]
Fixed
