### ISSUE TITLE
Back to top button 

### ISSUE THREAD

**Issue by Nupur19nj** [ctfguide-tech/CTFGuideNext#82]
I want to add back to top button please assign me this under hacktober-accepted!
![image](https://github.com/ctfguide-tech/CTFGuideNext/assets/114866308/015e7fa0-fc99-4595-bbdd-8ceb97f540fe)

**Comment by Laphatize** [comment]
Thanks for the suggestion. This would be useful for mobile users, but we have a revamped homepage in the works anyways - so we will not be needing this currently.
